export const MOCK_TENANTS = [
  {
    id: 1,
    name: "Department of Education",
    plan: "Institute",
    status: "Active",
    joined: "Jan 02 2026",
    end: "Jan 02 2027",
    abbr: "DepEd",
    color: "#2980b9",
    email: "deped@gmail.com",
    phone: "08-2249",
    facebook: "depedofficialfbpage",
    stats: { subscriptions: 3, management: 10, learners: 200, courses: 13 },
    courseActivity: [
      { name: "Sales Fundamentals",     progress: 82, totalUsers: 40 },
      { name: "Customer Service Pro",   progress: 65, totalUsers: 38 },
      { name: "Digital Marketing",      progress: 90, totalUsers: 42 },
      { name: "Technical Onboarding",   progress: 30, totalUsers: 35 },
      { name: "Leadership Basics",      progress: 55, totalUsers: 30 },
    ],
    lastActive: "2026-03-19",
  },
  {
    id: 2,
    name: "Eleksis Marketing Corp",
    plan: "Enterprise",
    status: "Active",
    joined: "Jan 10 2026",
    end: "Jan 10 2027",
    abbr: "ELEKSIS",
    color: "#c0392b",
    email: "eleksis@gmail.com",
    phone: "02-1234",
    facebook: "",
    stats: { subscriptions: 2, management: 5, learners: 320, courses: 20 },
    courseActivity: [
      { name: "Brand Strategy",         progress: 45, totalUsers: 60 },
      { name: "Social Media Marketing", progress: 72, totalUsers: 55 },
      { name: "Content Creation",       progress: 20, totalUsers: 50 },
      { name: "SEO Fundamentals",       progress: 10, totalUsers: 48 },
    ],
    lastActive: "2026-03-10",
  },
  {
    id: 3,
    name: "De La Salle University",
    plan: "Institute",
    status: "Active",
    joined: "Jan 01 2026",
    end: "Jan 01 2027",
    abbr: "DLSU",
    color: "#27ae60",
    email: "dlsu@gmail.com",
    phone: "02-5678",
    facebook: "",
    stats: { subscriptions: 2, management: 8, learners: 500, courses: 35 },
    courseActivity: [
      { name: "Engineering Principles", progress: 88, totalUsers: 120 },
      { name: "Research Methods",       progress: 76, totalUsers: 115 },
      { name: "Academic Writing",       progress: 91, totalUsers: 130 },
      { name: "Data Analysis",          progress: 60, totalUsers: 110 },
      { name: "Ethics in Tech",         progress: 44, totalUsers: 100 },
      { name: "Project Management",     progress: 70, totalUsers: 95  },
    ],
    lastActive: "2026-03-20",
  },
  {
    id: 4,
    name: "Zoup Sales and Marketing",
    plan: "Personal",
    status: "Active",
    joined: "Feb 01 2026",
    end: "Feb 01 2027",
    abbr: "ZOUP",
    color: "#8e44ad",
    email: "zoup@gmail.com",
    phone: "02-9999",
    facebook: "",
    stats: { subscriptions: 1, management: 3, learners: 32, courses: 8 },
    courseActivity: [
      { name: "Sales Techniques",       progress: 55, totalUsers: 10 },
      { name: "CRM Basics",             progress: 40, totalUsers: 9  },
      { name: "Cold Calling Mastery",   progress: 15, totalUsers: 8  },
    ],
    lastActive: "2026-03-08",
  },
  {
    id: 5,
    name: "Build Hub PH",
    plan: "Enterprise",
    status: "Inactive",
    joined: "Mar 01 2026",
    end: "Mar 01 2027",
    abbr: "BHUB",
    color: "#e67e22",
    email: "buildhub@gmail.com",
    phone: "02-0000",
    facebook: "",
    stats: { subscriptions: 1, management: 0, learners: 0, courses: 0 },
    courseActivity: [],
    lastActive: "2026-02-28",
  },
];
